apiVersion: v1
kind: Pod
metadata:
  name: devapp
  namespace: dev
  labels:
    app: devapp
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: devapp
  namespace: dev
spec:
  selector:
    app: devapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devapp
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/acme-challenge-type: http01    
    cert-manager.io/issuer: letsencrypt-staging    
spec:
  rules:
  - host: devapp.k8s.azcloud.top
    http:
      paths:
      - path: /
        backend:
          serviceName: devapp
          servicePort: 80
  tls:
  - hosts:
    - devapp.k8s.azcloud.top
    secretName: devapp-tls              