apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
spec:
  selector:
    app: aspnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aspnetapp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/acme-challenge-type: http01  
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: aspnetapp.k8s.azcloud.top  
    http:
      paths:
      - path: /
        backend:
          serviceName: aspnetapp
          servicePort: 80
  tls:
  - hosts:
    - aspnetapp.k8s.azcloud.top
    secretName: aspnetapp-k8s-tls             