apiVersion: v1
kind: Pod
metadata:
  name: sreapp
  namespace: sre
  labels:
    app: sreapp
spec:
  containers:
  - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
    name: aspnetapp-image
    ports:
    - containerPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: sreapp
  namespace: sre
spec:
  selector:
    app: sreapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sreapp
  namespace: sre
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: sreapp.k8s.azcloud.top  
    http:
      paths:
      - path: /
        backend:
          serviceName: sreapp
          servicePort: 80
          